### PR TITLE
Update stalin_sort.py

### PR DESCRIPTION
**Pull request by watosar**
I think this is more simple.

### CODE REVIEW

**Comment by gustavo-depaula** [comment]
instead of overriding the solution, please create a new file for this solution with list comprehension

**Comment by watosar** [comment]
Thanks for your reply.  I didn't think my solution was unique enough to be added as a new one. So, I'm surprised and glad at your comment. I will fix it now. 

But how I should do it? Sorry, I’m very poor at using git and Github.
Making new PR is better way?

**Comment by mogron** [comment]
I don't think this is still O(N), because you have nested loops over the list in your comprehension, right?

**Comment by gustavo-depaula** [comment]
@watosar I think you can do that by drag and dropping a new file to your repository and deleting the changes to the old one

**Comment by watosar** [comment]
@mogron 
> I don't think this is still O(N), because you have nested loops over the list in your comprehension, right?
  
I think I have only one loop.
```python 
[ 
    x 
    for max_val in l[:1] # not loop
    for x in l # loop
    if x >= max_val 
    for max_val in (x, ) # not loop
]
```

**Comment by mogron** [comment]
@watosar right, I misread the first "for"!

**Comment by mogron** [comment]
To be honest, I don't understand your solution :D

**Pull request merged**
