### PR TITLE
F# implementation.

### PR DESCRIPTION
**Pull request by rukletsov**

### CODE REVIEW

**Comment by gustavo-depaula** [comment]
what is the result of `1 2 4 4 3`?

**Comment by rukletsov** [comment]
> 1 2 4 4 3

`1 2 4`, since `<` is used as a comparison operation (looked at the C++ solution for that)

**Comment by gustavo-depaula** [comment]
Please use <= instead. We want those repeated numbers. I'll look at the C++ solution

**Comment by rukletsov** [comment]
@gustavo-depaula done!

**Pull request merged**
