### PR TITLE
Added R implementation for the betterment of the stats community

### PR DESCRIPTION
**Pull request by ebridge2**
plz accept.

### CODE REVIEW

**Comment by gabrielcarneiro97** [comment]
Hey friend, could you show the result for this array: [1, 2, 2, 5, 4, 5, 3, 7]

**Comment by ebridge2** [comment]
Hello guy,

```
print(stalin.sort(x, decreasing=FALSE, verbose=TRUE))
[1] "Don’t blame a mirror for your ugly face. To the gulag with 4!"
[1] "Trust; but verify. To the gulag with 3!"
[1] 1 2 2 5 5 7
```

**Comment by ebridge2** [comment]
I've also updated for make helpful message to guarantee the performance of algorithm:
```
source('~/Documents/research/Rpackages/stalin-sort/r/stalinsort.R')
[1] "Trust; but verify. To the gulag with 4!"
[1] "An old friend is better than two new friends. To the gulag with 3!"
[1] "A result stronk as Stalinium."
[1] 1 2 2 5 5 7
```

**Comment by gabrielcarneiro97** [comment]
Thanks for your contribution!
Feel free to help us with any other language that you're familiar with!

**Pull request merged**
