### PR TITLE
Add Stalin Sort in Common Lisp

### PR DESCRIPTION
**Pull request by luksamuk**

### CODE REVIEW

**Comment by chuntaro** [comment]
(stalin-sort '(3 1 2 5 4 7 6 9 8)) => (3 2 5 7 9) Oops!

**Comment by luksamuk** [comment]
> (stalin-sort '(3 1 2 5 4 7 6 9 8)) => (3 2 5 7 9) Oops!

Uh-oh! Hopefully it is fixed now.

**Comment by chuntaro** [comment]
(stalin-sort '(3 1 2 5 4 7 6 9 8)) => (3 5 7 9)
Python version
sort([3, 1, 2, 5, 5, 7, 6, 9, 8]) => [3, 5, 5, 7, 9]
The same value is output.

**Comment by luksamuk** [comment]
Seems like a small problem with the operator used to "remove" a number. It did not allow consecutive repeated numbers. It is now fixed, thanks.

```
CL-USER> (stalin-sort '(3 1 2 5 5 4 7 6 9 8))
(3 5 5 7 9)
```

**Comment by gustavo-depaula** [comment]
thanks @chuntaro for reviewing this!

**Pull request merged**
